### PR TITLE
Implement rule of zero

### LINKED ISSUE #76: Many objects are not std::move-able
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/76)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
In order to use `std::move` semantics in c++ (like assignment of unique_ptr's), objects need to have move constructor and move assignment operators defined (also known as the [rule of 5](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)#Rule_of_Five). This lets you do things like this:

~~~
std::unique_ptr<math::Pose3d> ptr1, ptr2;
ptr1.reset(new math::Pose3d);
ptr2 = ptr1;
~~~

but that doesn't currently work because we aren't following the rule of 5 for many of our classes. I mention this because I was trying to use it in a gazebo plugin and it didn't work. I've added some statements to unit tests in b25df8976d840625395e66cd8a0966d69d1405f6 that illustrate this failure to compile.

### PR DESCRIPTION
**Pull request by azeey**
Closes #76 

## Summary
Most of it was deleting copy constructors, assignment operators and destructors. SignalStats needed a change to make it use `gz::utils::ImplPtr`.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Comment by scpeters** [comment]
I see one compiler warning

~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__memory/unique_ptr.h:65:5: warning: delete called on 'gz::math::SignalStatistic' that is abstract but has non-virtual destructor [-Wdelete-abstract-non-virtual-dtor]
    delete __ptr;
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__memory/unique_ptr.h:297:7: note: in instantiation of member function 'std::default_delete<gz::math::SignalStatistic>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__memory/unique_ptr.h:263:75: note: in instantiation of member function 'std::unique_ptr<gz::math::SignalStatistic>::reset' requested here
  _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX23 ~unique_ptr() { reset(); }
                                                                          ^
/usr/local/include/pybind11/pybind11.h:1974:40: note: in instantiation of member function 'std::unique_ptr<gz::math::SignalStatistic>::~unique_ptr' requested here
            v_h.holder<holder_type>().~holder_type();
                                       ^
/usr/local/include/pybind11/pybind11.h:1634:26: note: in instantiation of member function 'pybind11::class_<gz::math::SignalStatistic, gz::math::python::SignalStatisticTrampoline>::dealloc' requested here
        record.dealloc = dealloc;
                         ^
/Users/jenkins/jenkins-agent/workspace/gz_math-ci-pr_any-homebrew-amd64/gz-math/src/python_pybind11/src/SignalStats.cc:124:3: note: in instantiation of function template specialization 'pybind11::class_<gz::math::SignalStatistic, gz::math::python::SignalStatisticTrampoline>::class_<pybind11::buffer_protocol, pybind11::dynamic_attr>' requested here
  py::class_<Class, SignalStatisticTrampoline>(m,
  ^
1 warning generated.
~~~

**Comment by Crola1702** [comment]
@azeey I think this PR created a regression in [gz_math8-install_bottle-homebrew-amd64](https://build.osrfoundation.org/view/gz-ionic/job/gz_math8-install_bottle-homebrew-amd64/241/console)

See log output:
```
In file included from test.cpp:1:
/usr/local/Cellar/gz-math8/7.999.999-0-20231006/include/gz/math8/gz/math/SignalStats.hh:25:10: fatal error: 'gz/utils/ImplPtr.hh' file not found
#include <gz/utils/ImplPtr.hh>
         ^~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
Error: osrf/simulation/gz-math8: failed
```

Maybe we're missing a release from gz-utils in homebrew?

**Comment by azeey** [comment]
It looks like there's a test in the homebrew formula that builds this with manual compiler flags
https://github.com/osrf/homebrew-simulation//blob/64970778c6b13cc22739a47dc7e5b67aa491b5cc/Formula/gz-math8.rb#L58.  I'll update it to add gz-utils. 

@scpeters do we actually need this test? I would have thought the CMake test would be sufficient.

**Comment by azeey** [comment]
@Crola1702, "fix" in https://github.com/osrf/homebrew-simulation/pull/2723

**Pull request merged**
