### PR TITLE
buffer_protocol for vectors and matrices in python bindings

### PR DESCRIPTION
**Pull request by unjambonakap**
This is an extension/takeover of https://github.com/gazebosim/gz-math/pull/498

## Summary

This change enables the buffer_protocol for `VectorX` and `MatrixYxY` so that `memoryiew` and `numpy.array` can be used on them

```
np.array(math7.Vector3())
memoryview(math7.Matrix3d())

list(math7.Vector2d())
>>> math7.Quaterniond().xyzw() # == [0.0, 0.0, 0.0, 1.0]
```
Additionally:
- IndexError is raised on invalid vector __getitem__/__setitem__ access. This way list(vector) works correctly instead of spinning
- A convenience Quaternion.xyzw() -> list is added

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to sign the commit?

**Comment by unjambonakap** [comment]
Tests are failing because of lack of numpy. Do you prefer to add numpy to the test environment or introducing this dependency is undesirable and I should rewrite the test to do away with numpy?

**Review by ahcorde — DISMISSED** [review]
you can add the dependency here https://github.com/gazebosim/gz-math/blob/gz-math7/.github/ci/packages.apt

**Comment by unjambonakap** [comment]
> you can add the dependency here https://github.com/gazebosim/gz-math/blob/gz-math7/.github/ci/packages.apt

Done, thanks for the pointer :pray:

**Comment by unjambonakap** [comment]
@ahcorde do you have additional pointers on why tests are failing? In particular, homebrew is missing numpy

**Comment by mjcarroll** [comment]
> do you have additional pointers on why tests are failing? In particular, homebrew is missing numpy

We generally don't add dependencies to stable releases.  If you could, retarget this to `main`, and we can work on landing it there first with the additional dependencies.

**Comment by azeey** [comment]
> We generally don't add dependencies to stable releases. If you could, retarget this to main, and we can work on landing it there first with the additional dependencies.
 
Agreed. Hopefully we can backport  to `gz-math7` without the numpy tests once it lands on `main`.

**Comment by willstott101** [comment]
Cool, thanks for taking this over.

Perhaps the comments could help explain a bit more what's going on?

      /// \brief Underlying data pointer
      /// \remarks This method is intended for python bindings (numpy).
      /// \remarks The bounds-checking array subscript operator is much preferred for element access from C++.
      /// \return A pointer to the underlying data array.

**Comment by arjo129** [comment]
Hi @unjambonakap , was wondering what the status on this was. Do we intend shipping this change with ionic (code freeze 26/8)? If we can't come to a consensus by then I will remove the beta label. For starters would it be possible for you to resolve the merge conflicts.

**Comment by arjo129** [comment]
Also as this PR breaks API can we plese target `main` and not `gz-math7`

**Review by arjo129 — CHANGES_REQUESTED** [review]
Thanks for these changes. I tested them and they mostly look good to me. There are some minor stylistic improvements that need to be made before I finally :heavy_check_mark:  them.

**Comment by azeey** [comment]
@unjambonakap any chance you can respond to the feedback in the next couple days? Since gz-math is a lower level library in the Gazebo stack, we'd like to wrap up PRs earlier to make sure there is enough time to test them before the code freeze (August 28th).

**Comment by unjambonakap** [comment]
By Monday I should get it done

**Comment by unjambonakap** [comment]
F. Sorry about that I was afk
Thanks for doing it

**Comment by azeey** [comment]
I didn't address some of the feedback. Mainly, I think it would be good to add c++ tests.

**Review by arjo129 — APPROVED** [review]

**Review by arjo129 — APPROVED** [review]
Thanks for iterating on this. LGTM.

**Pull request merged**
